/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package battlegraphs_v6;

/**
 *
 * @author Charlie
 */
public class GameScreen_V6 extends javax.swing.JPanel {

    /**
     * Creates new form GameScreen_V6
     */
    public GameScreen_V6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        gridDisplayArea = new javax.swing.JPanel();
        grid = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        infoDisplayArea = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(775, 455));
        setMinimumSize(new java.awt.Dimension(775, 455));
        setPreferredSize(new java.awt.Dimension(775, 455));

        gridDisplayArea.setBackground(new java.awt.Color(160, 160, 160));
        gridDisplayArea.setMaximumSize(new java.awt.Dimension(455, 455));
        gridDisplayArea.setMinimumSize(new java.awt.Dimension(455, 455));
        gridDisplayArea.setPreferredSize(new java.awt.Dimension(463, 453));
        gridDisplayArea.setLayout(null);

        grid.setBackground(new java.awt.Color(200, 200, 200));
        grid.setToolTipText("");
        grid.setAlignmentX(0.0F);
        grid.setAlignmentY(0.0F);
        grid.setMaximumSize(new java.awt.Dimension(438, 428));
        grid.setMinimumSize(new java.awt.Dimension(438, 428));
        grid.setPreferredSize(new java.awt.Dimension(438, 428));

        jLabel2.setBackground(new java.awt.Color(255, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("A2");
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setIconTextGap(0);
        jLabel2.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel2.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel2.setRequestFocusEnabled(false);
        grid.add(jLabel2);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("A1");
        jLabel3.setAlignmentY(0.0F);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setIconTextGap(0);
        jLabel3.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel3.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel3.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel3.setRequestFocusEnabled(false);
        grid.add(jLabel3);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("A4");
        jLabel4.setAlignmentY(0.0F);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setIconTextGap(0);
        jLabel4.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel4.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel4.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel4.setRequestFocusEnabled(false);
        grid.add(jLabel4);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("A3");
        jLabel5.setAlignmentY(0.0F);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setIconTextGap(0);
        jLabel5.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel5.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel5.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel5.setRequestFocusEnabled(false);
        grid.add(jLabel5);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("A6");
        jLabel6.setAlignmentY(0.0F);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setIconTextGap(0);
        jLabel6.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel6.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel6.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel6.setRequestFocusEnabled(false);
        grid.add(jLabel6);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("A5");
        jLabel7.setAlignmentY(0.0F);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setIconTextGap(0);
        jLabel7.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel7.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel7.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel7.setRequestFocusEnabled(false);
        grid.add(jLabel7);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("A8");
        jLabel8.setAlignmentY(0.0F);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setIconTextGap(0);
        jLabel8.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel8.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel8.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel8.setRequestFocusEnabled(false);
        grid.add(jLabel8);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("A7");
        jLabel9.setAlignmentY(0.0F);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setIconTextGap(0);
        jLabel9.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel9.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel9.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel9.setRequestFocusEnabled(false);
        grid.add(jLabel9);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("A9");
        jLabel11.setAlignmentY(0.0F);
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.setIconTextGap(0);
        jLabel11.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel11.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel11.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel11.setRequestFocusEnabled(false);
        grid.add(jLabel11);

        jLabel12.setBackground(new java.awt.Color(255, 0, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("A10");
        jLabel12.setAlignmentY(0.0F);
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setIconTextGap(0);
        jLabel12.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel12.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel12.setOpaque(true);
        jLabel12.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel12.setRequestFocusEnabled(false);
        grid.add(jLabel12);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("A10");
        jLabel13.setAlignmentY(0.0F);
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel13.setIconTextGap(0);
        jLabel13.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel13.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel13.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel13.setRequestFocusEnabled(false);
        grid.add(jLabel13);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("A9");
        jLabel14.setAlignmentY(0.0F);
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel14.setIconTextGap(0);
        jLabel14.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel14.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel14.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel14.setRequestFocusEnabled(false);
        grid.add(jLabel14);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("A8");
        jLabel10.setAlignmentY(0.0F);
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.setIconTextGap(0);
        jLabel10.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel10.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel10.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel10.setRequestFocusEnabled(false);
        grid.add(jLabel10);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("A7");
        jLabel15.setAlignmentY(0.0F);
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel15.setIconTextGap(0);
        jLabel15.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel15.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel15.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel15.setRequestFocusEnabled(false);
        grid.add(jLabel15);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("A6");
        jLabel16.setAlignmentY(0.0F);
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel16.setIconTextGap(0);
        jLabel16.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel16.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel16.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel16.setRequestFocusEnabled(false);
        grid.add(jLabel16);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("A5");
        jLabel17.setAlignmentY(0.0F);
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel17.setIconTextGap(0);
        jLabel17.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel17.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel17.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel17.setRequestFocusEnabled(false);
        grid.add(jLabel17);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("A3");
        jLabel18.setAlignmentY(0.0F);
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel18.setIconTextGap(0);
        jLabel18.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel18.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel18.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel18.setRequestFocusEnabled(false);
        grid.add(jLabel18);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("A4");
        jLabel19.setAlignmentY(0.0F);
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel19.setIconTextGap(0);
        jLabel19.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel19.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel19.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel19.setRequestFocusEnabled(false);
        grid.add(jLabel19);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("A2");
        jLabel20.setAlignmentY(0.0F);
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel20.setIconTextGap(0);
        jLabel20.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel20.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel20.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel20.setRequestFocusEnabled(false);
        grid.add(jLabel20);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("A1");
        jLabel21.setAlignmentY(0.0F);
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel21.setIconTextGap(0);
        jLabel21.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel21.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel21.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel21.setRequestFocusEnabled(false);
        grid.add(jLabel21);

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("A10");
        jLabel32.setAlignmentY(0.0F);
        jLabel32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel32.setIconTextGap(0);
        jLabel32.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel32.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel32.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel32.setRequestFocusEnabled(false);
        grid.add(jLabel32);

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("A10");
        jLabel33.setAlignmentY(0.0F);
        jLabel33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel33.setIconTextGap(0);
        jLabel33.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel33.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel33.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel33.setRequestFocusEnabled(false);
        grid.add(jLabel33);

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("A9");
        jLabel34.setAlignmentY(0.0F);
        jLabel34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel34.setIconTextGap(0);
        jLabel34.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel34.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel34.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel34.setRequestFocusEnabled(false);
        grid.add(jLabel34);

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("A9");
        jLabel35.setAlignmentY(0.0F);
        jLabel35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel35.setIconTextGap(0);
        jLabel35.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel35.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel35.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel35.setRequestFocusEnabled(false);
        grid.add(jLabel35);

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("A8");
        jLabel36.setAlignmentY(0.0F);
        jLabel36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel36.setIconTextGap(0);
        jLabel36.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel36.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel36.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel36.setRequestFocusEnabled(false);
        grid.add(jLabel36);

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("A8");
        jLabel37.setAlignmentY(0.0F);
        jLabel37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel37.setIconTextGap(0);
        jLabel37.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel37.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel37.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel37.setRequestFocusEnabled(false);
        grid.add(jLabel37);

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("A7");
        jLabel38.setAlignmentY(0.0F);
        jLabel38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel38.setIconTextGap(0);
        jLabel38.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel38.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel38.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel38.setRequestFocusEnabled(false);
        grid.add(jLabel38);

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("A7");
        jLabel39.setAlignmentY(0.0F);
        jLabel39.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel39.setIconTextGap(0);
        jLabel39.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel39.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel39.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel39.setRequestFocusEnabled(false);
        grid.add(jLabel39);

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("A6");
        jLabel40.setAlignmentY(0.0F);
        jLabel40.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel40.setIconTextGap(0);
        jLabel40.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel40.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel40.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel40.setRequestFocusEnabled(false);
        grid.add(jLabel40);

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("A6");
        jLabel41.setAlignmentY(0.0F);
        jLabel41.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel41.setIconTextGap(0);
        jLabel41.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel41.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel41.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel41.setRequestFocusEnabled(false);
        grid.add(jLabel41);

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("A5");
        jLabel42.setAlignmentY(0.0F);
        jLabel42.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel42.setIconTextGap(0);
        jLabel42.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel42.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel42.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel42.setRequestFocusEnabled(false);
        grid.add(jLabel42);

        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("A5");
        jLabel43.setAlignmentY(0.0F);
        jLabel43.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel43.setIconTextGap(0);
        jLabel43.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel43.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel43.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel43.setRequestFocusEnabled(false);
        grid.add(jLabel43);

        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("A3");
        jLabel44.setAlignmentY(0.0F);
        jLabel44.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel44.setIconTextGap(0);
        jLabel44.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel44.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel44.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel44.setRequestFocusEnabled(false);
        grid.add(jLabel44);

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("A3");
        jLabel45.setAlignmentY(0.0F);
        jLabel45.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel45.setIconTextGap(0);
        jLabel45.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel45.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel45.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel45.setRequestFocusEnabled(false);
        grid.add(jLabel45);

        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("A4");
        jLabel46.setAlignmentY(0.0F);
        jLabel46.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel46.setIconTextGap(0);
        jLabel46.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel46.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel46.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel46.setRequestFocusEnabled(false);
        grid.add(jLabel46);

        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("A4");
        jLabel47.setAlignmentY(0.0F);
        jLabel47.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel47.setIconTextGap(0);
        jLabel47.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel47.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel47.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel47.setRequestFocusEnabled(false);
        grid.add(jLabel47);

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("A2");
        jLabel48.setAlignmentY(0.0F);
        jLabel48.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel48.setIconTextGap(0);
        jLabel48.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel48.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel48.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel48.setRequestFocusEnabled(false);
        grid.add(jLabel48);

        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("A2");
        jLabel49.setAlignmentY(0.0F);
        jLabel49.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel49.setIconTextGap(0);
        jLabel49.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel49.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel49.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel49.setRequestFocusEnabled(false);
        grid.add(jLabel49);

        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("A1");
        jLabel50.setAlignmentY(0.0F);
        jLabel50.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel50.setIconTextGap(0);
        jLabel50.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel50.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel50.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel50.setRequestFocusEnabled(false);
        grid.add(jLabel50);

        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("A1");
        jLabel51.setAlignmentY(0.0F);
        jLabel51.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel51.setIconTextGap(0);
        jLabel51.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel51.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel51.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel51.setRequestFocusEnabled(false);
        grid.add(jLabel51);

        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("A10");
        jLabel52.setAlignmentY(0.0F);
        jLabel52.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel52.setIconTextGap(0);
        jLabel52.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel52.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel52.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel52.setRequestFocusEnabled(false);
        grid.add(jLabel52);

        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("A9");
        jLabel53.setAlignmentY(0.0F);
        jLabel53.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel53.setIconTextGap(0);
        jLabel53.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel53.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel53.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel53.setRequestFocusEnabled(false);
        grid.add(jLabel53);

        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("A8");
        jLabel54.setAlignmentY(0.0F);
        jLabel54.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel54.setIconTextGap(0);
        jLabel54.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel54.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel54.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel54.setRequestFocusEnabled(false);
        grid.add(jLabel54);

        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("A7");
        jLabel55.setAlignmentY(0.0F);
        jLabel55.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel55.setIconTextGap(0);
        jLabel55.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel55.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel55.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel55.setRequestFocusEnabled(false);
        grid.add(jLabel55);

        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("A6");
        jLabel56.setAlignmentY(0.0F);
        jLabel56.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel56.setIconTextGap(0);
        jLabel56.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel56.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel56.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel56.setRequestFocusEnabled(false);
        grid.add(jLabel56);

        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("A5");
        jLabel57.setAlignmentY(0.0F);
        jLabel57.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel57.setIconTextGap(0);
        jLabel57.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel57.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel57.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel57.setRequestFocusEnabled(false);
        grid.add(jLabel57);

        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("A3");
        jLabel58.setAlignmentY(0.0F);
        jLabel58.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel58.setIconTextGap(0);
        jLabel58.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel58.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel58.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel58.setRequestFocusEnabled(false);
        grid.add(jLabel58);

        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("A4");
        jLabel59.setAlignmentY(0.0F);
        jLabel59.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel59.setIconTextGap(0);
        jLabel59.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel59.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel59.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel59.setRequestFocusEnabled(false);
        grid.add(jLabel59);

        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("A2");
        jLabel60.setAlignmentY(0.0F);
        jLabel60.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel60.setIconTextGap(0);
        jLabel60.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel60.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel60.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel60.setRequestFocusEnabled(false);
        grid.add(jLabel60);

        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("A1");
        jLabel61.setAlignmentY(0.0F);
        jLabel61.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel61.setIconTextGap(0);
        jLabel61.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel61.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel61.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel61.setRequestFocusEnabled(false);
        grid.add(jLabel61);

        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("A2");
        jLabel62.setAlignmentY(0.0F);
        jLabel62.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel62.setIconTextGap(0);
        jLabel62.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel62.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel62.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel62.setRequestFocusEnabled(false);
        grid.add(jLabel62);

        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("A10");
        jLabel63.setAlignmentY(0.0F);
        jLabel63.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel63.setIconTextGap(0);
        jLabel63.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel63.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel63.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel63.setRequestFocusEnabled(false);
        grid.add(jLabel63);

        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("A1");
        jLabel64.setAlignmentY(0.0F);
        jLabel64.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel64.setIconTextGap(0);
        jLabel64.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel64.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel64.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel64.setRequestFocusEnabled(false);
        grid.add(jLabel64);

        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("A10");
        jLabel65.setAlignmentY(0.0F);
        jLabel65.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel65.setIconTextGap(0);
        jLabel65.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel65.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel65.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel65.setRequestFocusEnabled(false);
        grid.add(jLabel65);

        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("A4");
        jLabel66.setAlignmentY(0.0F);
        jLabel66.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel66.setIconTextGap(0);
        jLabel66.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel66.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel66.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel66.setRequestFocusEnabled(false);
        grid.add(jLabel66);

        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("A9");
        jLabel67.setAlignmentY(0.0F);
        jLabel67.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel67.setIconTextGap(0);
        jLabel67.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel67.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel67.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel67.setRequestFocusEnabled(false);
        grid.add(jLabel67);

        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("A3");
        jLabel68.setAlignmentY(0.0F);
        jLabel68.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel68.setIconTextGap(0);
        jLabel68.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel68.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel68.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel68.setRequestFocusEnabled(false);
        grid.add(jLabel68);

        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel69.setText("A9");
        jLabel69.setAlignmentY(0.0F);
        jLabel69.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel69.setIconTextGap(0);
        jLabel69.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel69.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel69.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel69.setRequestFocusEnabled(false);
        grid.add(jLabel69);

        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText("A6");
        jLabel70.setAlignmentY(0.0F);
        jLabel70.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel70.setIconTextGap(0);
        jLabel70.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel70.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel70.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel70.setRequestFocusEnabled(false);
        grid.add(jLabel70);

        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel71.setText("A8");
        jLabel71.setAlignmentY(0.0F);
        jLabel71.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel71.setIconTextGap(0);
        jLabel71.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel71.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel71.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel71.setRequestFocusEnabled(false);
        grid.add(jLabel71);

        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText("A5");
        jLabel72.setAlignmentY(0.0F);
        jLabel72.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel72.setIconTextGap(0);
        jLabel72.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel72.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel72.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel72.setRequestFocusEnabled(false);
        grid.add(jLabel72);

        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("A8");
        jLabel73.setAlignmentY(0.0F);
        jLabel73.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel73.setIconTextGap(0);
        jLabel73.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel73.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel73.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel73.setRequestFocusEnabled(false);
        grid.add(jLabel73);

        jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel74.setText("A8");
        jLabel74.setAlignmentY(0.0F);
        jLabel74.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel74.setIconTextGap(0);
        jLabel74.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel74.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel74.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel74.setRequestFocusEnabled(false);
        grid.add(jLabel74);

        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel75.setText("A7");
        jLabel75.setAlignmentY(0.0F);
        jLabel75.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel75.setIconTextGap(0);
        jLabel75.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel75.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel75.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel75.setRequestFocusEnabled(false);
        grid.add(jLabel75);

        jLabel76.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel76.setText("A7");
        jLabel76.setAlignmentY(0.0F);
        jLabel76.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel76.setIconTextGap(0);
        jLabel76.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel76.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel76.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel76.setRequestFocusEnabled(false);
        grid.add(jLabel76);

        jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel77.setText("A7");
        jLabel77.setAlignmentY(0.0F);
        jLabel77.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel77.setIconTextGap(0);
        jLabel77.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel77.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel77.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel77.setRequestFocusEnabled(false);
        grid.add(jLabel77);

        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel78.setText("A6");
        jLabel78.setAlignmentY(0.0F);
        jLabel78.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel78.setIconTextGap(0);
        jLabel78.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel78.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel78.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel78.setRequestFocusEnabled(false);
        grid.add(jLabel78);

        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel79.setText("A6");
        jLabel79.setAlignmentY(0.0F);
        jLabel79.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel79.setIconTextGap(0);
        jLabel79.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel79.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel79.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel79.setRequestFocusEnabled(false);
        grid.add(jLabel79);

        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel80.setText("A5");
        jLabel80.setAlignmentY(0.0F);
        jLabel80.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel80.setIconTextGap(0);
        jLabel80.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel80.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel80.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel80.setRequestFocusEnabled(false);
        grid.add(jLabel80);

        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel81.setText("A9");
        jLabel81.setAlignmentY(0.0F);
        jLabel81.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel81.setIconTextGap(0);
        jLabel81.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel81.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel81.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel81.setRequestFocusEnabled(false);
        grid.add(jLabel81);

        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel82.setText("A5");
        jLabel82.setAlignmentY(0.0F);
        jLabel82.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel82.setIconTextGap(0);
        jLabel82.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel82.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel82.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel82.setRequestFocusEnabled(false);
        grid.add(jLabel82);

        jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel83.setText("A3");
        jLabel83.setAlignmentY(0.0F);
        jLabel83.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel83.setIconTextGap(0);
        jLabel83.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel83.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel83.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel83.setRequestFocusEnabled(false);
        grid.add(jLabel83);

        jLabel84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel84.setText("A3");
        jLabel84.setAlignmentY(0.0F);
        jLabel84.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel84.setIconTextGap(0);
        jLabel84.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel84.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel84.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel84.setRequestFocusEnabled(false);
        grid.add(jLabel84);

        jLabel85.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel85.setText("A4");
        jLabel85.setAlignmentY(0.0F);
        jLabel85.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel85.setIconTextGap(0);
        jLabel85.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel85.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel85.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel85.setRequestFocusEnabled(false);
        grid.add(jLabel85);

        jLabel86.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel86.setText("A4");
        jLabel86.setAlignmentY(0.0F);
        jLabel86.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel86.setIconTextGap(0);
        jLabel86.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel86.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel86.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel86.setRequestFocusEnabled(false);
        grid.add(jLabel86);

        jLabel87.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel87.setText("A2");
        jLabel87.setAlignmentY(0.0F);
        jLabel87.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel87.setIconTextGap(0);
        jLabel87.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel87.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel87.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel87.setRequestFocusEnabled(false);
        grid.add(jLabel87);

        jLabel88.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel88.setText("A2");
        jLabel88.setAlignmentY(0.0F);
        jLabel88.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel88.setIconTextGap(0);
        jLabel88.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel88.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel88.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel88.setRequestFocusEnabled(false);
        grid.add(jLabel88);

        jLabel89.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel89.setText("A1");
        jLabel89.setAlignmentY(0.0F);
        jLabel89.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel89.setIconTextGap(0);
        jLabel89.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel89.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel89.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel89.setRequestFocusEnabled(false);
        grid.add(jLabel89);

        jLabel90.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel90.setText("A1");
        jLabel90.setAlignmentY(0.0F);
        jLabel90.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel90.setIconTextGap(0);
        jLabel90.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel90.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel90.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel90.setRequestFocusEnabled(false);
        grid.add(jLabel90);

        jLabel91.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel91.setText("A10");
        jLabel91.setAlignmentY(0.0F);
        jLabel91.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel91.setIconTextGap(0);
        jLabel91.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel91.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel91.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel91.setRequestFocusEnabled(false);
        grid.add(jLabel91);

        jLabel92.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel92.setText("A6");
        jLabel92.setAlignmentY(0.0F);
        jLabel92.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel92.setIconTextGap(0);
        jLabel92.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel92.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel92.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel92.setRequestFocusEnabled(false);
        grid.add(jLabel92);

        jLabel93.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel93.setText("A6");
        jLabel93.setAlignmentY(0.0F);
        jLabel93.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel93.setIconTextGap(0);
        jLabel93.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel93.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel93.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel93.setRequestFocusEnabled(false);
        grid.add(jLabel93);

        jLabel94.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel94.setText("A5");
        jLabel94.setAlignmentY(0.0F);
        jLabel94.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel94.setIconTextGap(0);
        jLabel94.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel94.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel94.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel94.setRequestFocusEnabled(false);
        grid.add(jLabel94);

        jLabel95.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel95.setText("A5");
        jLabel95.setAlignmentY(0.0F);
        jLabel95.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel95.setIconTextGap(0);
        jLabel95.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel95.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel95.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel95.setRequestFocusEnabled(false);
        grid.add(jLabel95);

        jLabel96.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel96.setText("A3");
        jLabel96.setAlignmentY(0.0F);
        jLabel96.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel96.setIconTextGap(0);
        jLabel96.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel96.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel96.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel96.setRequestFocusEnabled(false);
        grid.add(jLabel96);

        jLabel97.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel97.setText("A3");
        jLabel97.setAlignmentY(0.0F);
        jLabel97.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel97.setIconTextGap(0);
        jLabel97.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel97.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel97.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel97.setRequestFocusEnabled(false);
        grid.add(jLabel97);

        jLabel98.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel98.setText("A4");
        jLabel98.setAlignmentY(0.0F);
        jLabel98.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel98.setIconTextGap(0);
        jLabel98.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel98.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel98.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel98.setRequestFocusEnabled(false);
        grid.add(jLabel98);

        jLabel99.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel99.setText("A4");
        jLabel99.setAlignmentY(0.0F);
        jLabel99.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel99.setIconTextGap(0);
        jLabel99.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel99.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel99.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel99.setRequestFocusEnabled(false);
        grid.add(jLabel99);

        jLabel100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel100.setText("A2");
        jLabel100.setAlignmentY(0.0F);
        jLabel100.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel100.setIconTextGap(0);
        jLabel100.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel100.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel100.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel100.setRequestFocusEnabled(false);
        grid.add(jLabel100);

        jLabel101.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel101.setText("A2");
        jLabel101.setAlignmentY(0.0F);
        jLabel101.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel101.setIconTextGap(0);
        jLabel101.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel101.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel101.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel101.setRequestFocusEnabled(false);
        grid.add(jLabel101);

        jLabel102.setBackground(new java.awt.Color(255, 0, 255));
        jLabel102.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel102.setText("A1");
        jLabel102.setAlignmentY(0.0F);
        jLabel102.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel102.setIconTextGap(0);
        jLabel102.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel102.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel102.setOpaque(true);
        jLabel102.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel102.setRequestFocusEnabled(false);
        grid.add(jLabel102);

        jLabel103.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel103.setText("A1");
        jLabel103.setAlignmentY(0.0F);
        jLabel103.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel103.setIconTextGap(0);
        jLabel103.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel103.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel103.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel103.setRequestFocusEnabled(false);
        grid.add(jLabel103);

        jLabel104.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel104.setText("A10");
        jLabel104.setAlignmentY(0.0F);
        jLabel104.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel104.setIconTextGap(0);
        jLabel104.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel104.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel104.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel104.setRequestFocusEnabled(false);
        grid.add(jLabel104);

        jLabel105.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel105.setText("A10");
        jLabel105.setAlignmentY(0.0F);
        jLabel105.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel105.setIconTextGap(0);
        jLabel105.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel105.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel105.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel105.setRequestFocusEnabled(false);
        grid.add(jLabel105);

        jLabel106.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel106.setText("A9");
        jLabel106.setAlignmentY(0.0F);
        jLabel106.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel106.setIconTextGap(0);
        jLabel106.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel106.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel106.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel106.setRequestFocusEnabled(false);
        grid.add(jLabel106);

        jLabel107.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel107.setText("A9");
        jLabel107.setAlignmentY(0.0F);
        jLabel107.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel107.setIconTextGap(0);
        jLabel107.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel107.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel107.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel107.setRequestFocusEnabled(false);
        grid.add(jLabel107);

        jLabel108.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel108.setText("A8");
        jLabel108.setAlignmentY(0.0F);
        jLabel108.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel108.setIconTextGap(0);
        jLabel108.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel108.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel108.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel108.setRequestFocusEnabled(false);
        grid.add(jLabel108);

        jLabel109.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel109.setText("A8");
        jLabel109.setAlignmentY(0.0F);
        jLabel109.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel109.setIconTextGap(0);
        jLabel109.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel109.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel109.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel109.setRequestFocusEnabled(false);
        grid.add(jLabel109);

        jLabel110.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel110.setText("A7");
        jLabel110.setAlignmentY(0.0F);
        jLabel110.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel110.setIconTextGap(0);
        jLabel110.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel110.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel110.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel110.setRequestFocusEnabled(false);
        grid.add(jLabel110);

        jLabel111.setBackground(new java.awt.Color(255, 0, 255));
        jLabel111.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel111.setText("A7");
        jLabel111.setAlignmentY(0.0F);
        jLabel111.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel111.setIconTextGap(0);
        jLabel111.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel111.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel111.setOpaque(true);
        jLabel111.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel111.setRequestFocusEnabled(false);
        grid.add(jLabel111);

        gridDisplayArea.add(grid);
        grid.setBounds(10, 10, 470, 480);

        infoDisplayArea.setBackground(new java.awt.Color(180, 180, 180));
        infoDisplayArea.setMaximumSize(new java.awt.Dimension(310, 455));
        infoDisplayArea.setMinimumSize(new java.awt.Dimension(310, 455));
        infoDisplayArea.setPreferredSize(new java.awt.Dimension(310, 455));

        javax.swing.GroupLayout infoDisplayAreaLayout = new javax.swing.GroupLayout(infoDisplayArea);
        infoDisplayArea.setLayout(infoDisplayAreaLayout);
        infoDisplayAreaLayout.setHorizontalGroup(
            infoDisplayAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        infoDisplayAreaLayout.setVerticalGroup(
            infoDisplayAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gridDisplayArea, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(infoDisplayArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gridDisplayArea, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
            .addComponent(infoDisplayArea, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel grid;
    private javax.swing.JPanel gridDisplayArea;
    private javax.swing.JPanel infoDisplayArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    // End of variables declaration//GEN-END:variables
}
